/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:029b1868-2876-40a2-9d79-c03d56f62b59",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_AkIvbMw7l",
    "aws_user_pools_web_client_id": "5ickg3672nufg9lbc1mq5b4ead",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kqtwty7eijc5hhd74fx7z7vgp4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "korobka48d121d45ebe456486a8adf23f6db64405605-master",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
